// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	request "apiracer/request"

	mock "github.com/stretchr/testify/mock"
)

// APIClient is an autogenerated mock type for the APIClient type
type APIClient struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: url
func (_m *APIClient) Fetch(url string) (*request.APIResponse, error) {
	ret := _m.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 *request.APIResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*request.APIResponse, error)); ok {
		return rf(url)
	}
	if rf, ok := ret.Get(0).(func(string) *request.APIResponse); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.APIResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAPIClient creates a new instance of APIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *APIClient {
	mock := &APIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
